# Generated by Django 3.1.4 on 2020-12-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_expenses', models.IntegerField()),
                ('expense_source', models.CharField(max_length=50)),
                ('expense_amount', models.IntegerField()),
                ('expense_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='income_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('income_source', models.CharField(max_length=50)),
                ('income_amount', models.IntegerField()),
                ('income_date', models.DateField()),
            ],
        ),
    ]
